name: Makefile CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: initilize 
      run: make init-dist
      
    - name: make everything
      run: make all

    - name: Build dist
      run: make build-dist
      
