name: Portainer-GenX CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4
    
    # Step 2: Initialize the `dist` directory
    - name: Initialize
      run: make init-dist
      
    # Step 2.1: Update Browserslist DB
    - name: Update Browserslist DB
      run: npx update-browserslist-db@latest

    # Step 3: Build everything (client and server)
    - name: Build Everything
      run: make all

    # Step 4: Build the Docker image
    - name: Build Docker Image
      run: make build-image

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # Debugging step - List Docker images
    - name: List Docker Images
      run: docker images
      
    # Step 6: Re-Tag the Docker Image
    - name: Re-Tag Docker Image
      run: |
        docker tag portainerci/portainer-ce:local ${{ secrets.DOCKER_USERNAME }}/portainer-genx:latest
        
    # Step 7: Push the Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/portainer-genx:latest

