name: Portainer-GenX CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4
    
    # Step 2: Initialize the `dist` directory
    - name: Initialize
      run: make init-dist

    # Step 3: Build everything (client and server)
    - name: Build Everything
      run: make all

    # Step 4: Build the Docker image
    - name: Build Docker Image
      run: make build-image

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Tag and Push the Docker Image
    - name: Push Docker Image
      run: |
        docker tag portainerci/portainer-ce:local your-dockerhub-username/portainer-genx:latest
        docker push your-dockerhub-username/portainer-genx:latest
